name: offline-neuroloop

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - pyyaml
  - tqdm
  - scikit-learn
  - ipykernel
  - matplotlib
  - seaborn
  - swig
  - gymnasium
  - box2d-py
  - pip:
    - pygame==2.6.1
    - torch
    - gymnasium_robotics
    # - gym[box2d]
