name: offline_neuro_loop

channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pyyaml
  - tqdm
  - scikit-learn
  - ipykernel
  - matplotlib
  - seaborn
  - swig
  - gymnasium
  - box2d-py
  - pip:
    - pygame==2.6.1
    - torch
    - gymnasium-robotics
    - gym[box2d]
