name: offline_neuro_loop

channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pyyaml
  - torch
  - pygame
  - tqdm
  - scikit-learn
  - gymnasium_robotics
  - ipykernel
  - matplotlib
  - seaborn
  - swig
  - gymnasium
  - box2d-py
  - gym[box2d]