experiment:
  domain: "Flappy Bird"    
  pretrained_success_rate: 0.0

mlp:
  binary_hidden_layer_sizes: [30, 15, 5]
  ternary_hidden_layer_sizes: [75, 50, 5]
  regressor_hidden_layer_sizes: [100, 40, 2]
  binary_activation: "relu"
  ternary_activation: "relu"
  reg_activation: "tanh"
  binary_alpha: 0.0005
  ternary_alpha: 0.0001
  reg_alpha: 0.0005
  early_stopping: True
  
rl:
  n_episodes: 1000000
  algorithm: "DQN"
  steps: 800
  action_space: 2
  observation_space: 12
