experiment:
  domain: "Lunar Lander"
  pretrained_success_rate: 0.0

mlp:
  binary_hidden_layer_sizes: [10, 5, 2]
  ternary_hidden_layer_sizes: [10, 10, 3]
  regressor_hidden_layer_sizes: [20, 10, 3]
  clf_activation: "relu"
  reg_activation: "tanh"
  
rl:
  n_episodes: 1
  algorithm: "DQN"
  steps: 600
  action_space: 4
  observation_space: 11