experiment:
  domain: "Robot"                 

mlp:
  binary_hidden_layer_sizes: [10, 4, 2]
  ternary_hidden_layer_sizes: [18, 5, 3]
  regressor_hidden_layer_sizes: [20, 6, 2]
  clf_activation: "relu"
  reg_activation: "tanh"

rl:
  n_episodes: 150000 #500000
  algorithm: "DDPG"
  steps: 75
  action_space: None
  observation_space: None
