experiment:
  domain: "Robot"  
  pretrained_success_rate: 40.0

mlp:
  binary_hidden_layer_sizes: [75, 50, 5]
  ternary_hidden_layer_sizes: [80, 50, 5]
  regressor_hidden_layer_sizes: [150, 75, 5]
  binary_activation: "relu"
  ternary_activation: "relu"
  reg_activation: "relu"
  binary_alpha: 0.0005
  ternary_alpha: 0.0001
  reg_alpha: 0.0005
  early_stopping: True

rl:
  n_episodes: 20000
  algorithm: "DDPG"
  steps: 50
  action_space: None
  observation_space: None
