experiment: 
  domain: "Flappy"                        
  task: "Pooled"                         # Passive | Active | Pooled    
  model_granularity: "binary"             # binary | ternary | continuous
  participant_list: [2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  random_state: 42
  eval_update: 1000
  integration_type: "baseline"
  pretrained_success_rate: 0.0
  finetune_threshold: 0.0
  verbose: False

neural:
  smoothing_window_size: 1      # 1 for no smoothing, 2 for 2-point smoothing, etc.
  temporal_shift: 0.0         # 0.0 for no temporal shift, 0.1 for 0.1 second temporal shift, etc.
  window_size_s: 4.0          # 4.0 seconds for 4-second window, 5.0 seconds for 5-second window, etc.
  step_size_s: 1.0
  sliding_window_size: 1      # 1 for no sliding window, 2 for 2-point sliding window, etc.
  beta: 1.0                  # 1.0 for no beta, 2.0 for 2.0 beta, etc.
  fnirs_rate_hz: 5.2        # CONSTANT

mlp:
  model_noise: 0.0
  binary_hidden_layer_sizes: [50, 20, 5] # CONSTANT
  ternary_hidden_layer_sizes: [75, 50, 5] # CONSTANT
  regressor_hidden_layer_sizes: [100, 40, 2] # CONSTANT
  binary_activation: "relu" # CONSTANT
  ternary_activation: "relu" # CONSTANT
  reg_activation: "tanh" # CONSTANT
  binary_alpha: 0.0005 # CONSTANT
  ternary_alpha: 0.0001 # CONSTANT
  reg_alpha: 0.0005 # CONSTANT
  early_stopping: True # CONSTANT

rl:
  n_episodes: 2000 # CONSTANT
  algorithm: "DQN"
  buffer_type: "PER"
  learning_rate_init: 0.001
  steps: 1000  # CONSTANT
  action_space: 2 # CONSTANT
  observation_space: 12 # CONSTANT

